### ISSUE TITLE
I need an article from you in your blog. I'm sorry to trouble you. 

### ISSUE THREAD

**Issue by yeyingyun** [bjchan9an/control-flow-deflat#1]
LLVM程序分析日记之插桩BranchInst 

On how to use llvm to insert ifthen structure.

**Comment by bjchan9an** [comment]
We noticed that you are also interested in fuzz testing. We really recommend you to read the source code of Angora where you can learn about how to instrument ``llvm::BranchInst`` ;)

**Comment by yeyingyun** [comment]
Thanks!
